---
- name: Reload initd
  command: initctl reload-configuration

- name: Restart kafkaui service
  service:
    name: kafkaui
    state: restarted
  when: kafkaui_restart

- name: Restart kafkaui systemd
  systemd:
    name: kafkaui
    state: restarted
    daemon_reload: yes
  when: kafkaui_restart
